services:
  db:
    image: postgres:15-alpine
    container_name: goodhamburger_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: GoodHamburgerDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - goodhamburger-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: goodhamburger_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8432:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - goodhamburger-network

  lgtm:
    image: grafana/otel-lgtm:latest
    container_name: goodhamburger_lgtm
    restart: always
    ports:
      - "3000:3000"   # Grafana UI
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "9411:9411"   # Zipkin receiver
    volumes:
      - lgtm_data:/data
    networks:
      - goodhamburger-network

  api:
    build:
      context: ../../..
      dockerfile: BackEnd/4-Presentation/GoodHamburger.Api/Dockerfile
    container_name: goodhamburger_api
    restart: always
    ports:
      - "8500:8080"
      - "8501:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=GoodHamburgerDb;Username=admin;Password=password123
      - SRE__OtlpEndpointUrl=http://lgtm:4317
      - SRE__Nome=GoodHamburger.Api.Docker
      - SRE__Habilitado=true
      - SRE__UtilizaConsoleLog=true
    depends_on:
      - db
      - lgtm
    networks:
      - goodhamburger-network

  frontend:
    build:
      context: ../../..
      dockerfile: FrontEnd/GoodHamburger.FrontEnd/Dockerfile
    container_name: goodhamburger_frontend
    restart: always
    ports:
      - "3001:80"
    environment:
      - ApiBaseUrl=http://api:8080
    depends_on:
      - api
    networks:
      - goodhamburger-network

networks:
  goodhamburger-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  lgtm_data:
    driver: local
