services:
  db:
    image: postgres:15-alpine
    container_name: goodhamburger_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: GoodHamburgerDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: goodhamburger_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8432:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goodhamburger_api
    restart: always
    ports:
      - "8500:8080"
      - "8501:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=GoodHamburgerDb;Username=admin;Password=password123
    depends_on:
      - db
    networks:
      - goodhamburger-network

networks:
  goodhamburger-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
